package com.solo.tasky.ui.theme

import androidx.compose.ui.graphics.Color

val DarkBlue = Color(0xFF3949AB)


val Black = Color(0xFF171719)
val LightBlack = Color(0xFF23221F)
val LightText = Color(0xFF818488)
val White = Color(0xDCFFFFFF)
val DarkWhite = Color(0x33FFFFFF)
val ProgressBarColor = Color(0xFF3D454B)
val GreenDone = Color(0xFF6BC950)

val Purple = Color(0xFF714DD9)
val PurpleLight = Color(0xFF7F5FDD)
val PurpleText = Color(0xFFCBBEF2)

val Blue = Color(0xFF1F96F3)
val BlueLight = Color(0xFF339DF0)
val BlueText = Color(0xFF78BEF5)

val Green = Color(0xFF12B57A)
val GreenLight = Color(0xFF2ABC87)
val GreenText = Color(0xFFA4E2CB)

val RedPink = Color(0xfff48fb1)
val RedPinkLight = Color(0xFFF7CDDB)
val RedPinkText = Color(0xFFF1D6DF)

val RedOrange = Color(0xffffab91)
val RedOrangeLight = Color(0xFFF3CCC2)
val RedOrangeText = Color(0xFFF8E0D9)


val BabyBlue = Color(0xFF1FD5EC)
val BabyBlueLight = Color(0xFF7CDBE9)
val BabyBlueText = Color(0xFFDFF4F7)


val Violet = Color(0xffcf94da)
val VioletLight = Color(0xFFF0C8F7)
val VioletText = Color(0xFFEBDDEE)


val LemonYellow = Color(0xFFE1EB76)
val LemonYellowLight = Color(0xFFEBF598)
val LemonYellowText = Color(0xFFF4F5E9)


//dark theme colors


val primaryLight = Color(0xFF676013)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFF0E58B)
val onPrimaryContainerLight = Color(0xFF1F1C00)
val secondaryLight = Color(0xFF4D5C92)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFDCE1FF)
val onSecondaryContainerLight = Color(0xFF04174B)
val tertiaryLight = Color(0xFF525A92)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFDEE0FF)
val onTertiaryContainerLight = Color(0xFF0C154B)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFEF9EB)
val onBackgroundLight = Color(0xFF1D1C14)
val surfaceLight = Color(0xFFFEF9EB)
val onSurfaceLight = Color(0xFF1D1C14)
val surfaceVariantLight = Color(0xFFE8E2D0)
val onSurfaceVariantLight = Color(0xFF49473A)
val outlineLight = Color(0xFF7B7768)
val outlineVariantLight = Color(0xFFCBC6B5)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF323127)
val inverseOnSurfaceLight = Color(0xFFF6F0E3)
val inversePrimaryLight = Color(0xFFD3C972)
val surfaceDimLight = Color(0xFFDFDACC)
val surfaceBrightLight = Color(0xFFFEF9EB)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF8F3E5)
val surfaceContainerLight = Color(0xFFF3EEE0)
val surfaceContainerHighLight = Color(0xFFEDE8DA)
val surfaceContainerHighestLight = Color(0xFFE7E2D5)

val primaryLightMediumContrast = Color(0xFF4A4400)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF7E7629)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF314074)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF6372AA)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF363F74)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF6871AA)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF8C0009)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFDA342E)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFEF9EB)
val onBackgroundLightMediumContrast = Color(0xFF1D1C14)
val surfaceLightMediumContrast = Color(0xFFFEF9EB)
val onSurfaceLightMediumContrast = Color(0xFF1D1C14)
val surfaceVariantLightMediumContrast = Color(0xFFE8E2D0)
val onSurfaceVariantLightMediumContrast = Color(0xFF454336)
val outlineLightMediumContrast = Color(0xFF625F51)
val outlineVariantLightMediumContrast = Color(0xFF7E7B6C)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF323127)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF6F0E3)
val inversePrimaryLightMediumContrast = Color(0xFFD3C972)
val surfaceDimLightMediumContrast = Color(0xFFDFDACC)
val surfaceBrightLightMediumContrast = Color(0xFFFEF9EB)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF8F3E5)
val surfaceContainerLightMediumContrast = Color(0xFFF3EEE0)
val surfaceContainerHighLightMediumContrast = Color(0xFFEDE8DA)
val surfaceContainerHighestLightMediumContrast = Color(0xFFE7E2D5)

val primaryLightHighContrast = Color(0xFF272300)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF4A4400)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF0C1E52)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF314074)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF141D52)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF363F74)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF4E0002)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF8C0009)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFEF9EB)
val onBackgroundLightHighContrast = Color(0xFF1D1C14)
val surfaceLightHighContrast = Color(0xFFFEF9EB)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFE8E2D0)
val onSurfaceVariantLightHighContrast = Color(0xFF262419)
val outlineLightHighContrast = Color(0xFF454336)
val outlineVariantLightHighContrast = Color(0xFF454336)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF323127)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFFAEE93)
val surfaceDimLightHighContrast = Color(0xFFDFDACC)
val surfaceBrightLightHighContrast = Color(0xFFFEF9EB)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF8F3E5)
val surfaceContainerLightHighContrast = Color(0xFFF3EEE0)
val surfaceContainerHighLightHighContrast = Color(0xFFEDE8DA)
val surfaceContainerHighestLightHighContrast = Color(0xFFE7E2D5)

val primaryDark = Color(0xFFD3C972)
val onPrimaryDark = Color(0xFF363100)
val primaryContainerDark = Color(0xFF4E4800)
val onPrimaryContainerDark = Color(0xFFF0E58B)
val secondaryDark = Color(0xFFB6C4FF)
val onSecondaryDark = Color(0xFF1D2D61)
val secondaryContainerDark = Color(0xFF354479)
val onSecondaryContainerDark = Color(0xFFDCE1FF)
val tertiaryDark = Color(0xFFBBC3FF)
val onTertiaryDark = Color(0xFF232C61)
val tertiaryContainerDark = Color(0xFF3A4379)
val onTertiaryContainerDark = Color(0xFFDEE0FF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF15140C)
val onBackgroundDark = Color(0xFFE7E2D5)
val surfaceDark = Color(0xFF15140C)
val onSurfaceDark = Color(0xFFE7E2D5)
val surfaceVariantDark = Color(0xFF49473A)
val onSurfaceVariantDark = Color(0xFFCBC6B5)
val outlineDark = Color(0xFF959181)
val outlineVariantDark = Color(0xFF49473A)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE7E2D5)
val inverseOnSurfaceDark = Color(0xFF323127)
val inversePrimaryDark = Color(0xFF676013)
val surfaceDimDark = Color(0xFF15140C)
val surfaceBrightDark = Color(0xFF3B3930)
val surfaceContainerLowestDark = Color(0xFF0F0E07)
val surfaceContainerLowDark = Color(0xFF1D1C14)
val surfaceContainerDark = Color(0xFF212017)
val surfaceContainerHighDark = Color(0xFF2C2A21)
val surfaceContainerHighestDark = Color(0xFF37352C)

val primaryDarkMediumContrast = Color(0xFFD8CD76)
val onPrimaryDarkMediumContrast = Color(0xFF1A1700)
val primaryContainerDarkMediumContrast = Color(0xFF9C9242)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFBCC8FF)
val onSecondaryDarkMediumContrast = Color(0xFF001144)
val secondaryContainerDarkMediumContrast = Color(0xFF808EC8)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFC0C7FF)
val onTertiaryDarkMediumContrast = Color(0xFF050F46)
val tertiaryContainerDarkMediumContrast = Color(0xFF858DC8)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFBAB1)
val onErrorDarkMediumContrast = Color(0xFF370001)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF15140C)
val onBackgroundDarkMediumContrast = Color(0xFFE7E2D5)
val surfaceDarkMediumContrast = Color(0xFF15140C)
val onSurfaceDarkMediumContrast = Color(0xFFFFFAF2)
val surfaceVariantDarkMediumContrast = Color(0xFF49473A)
val onSurfaceVariantDarkMediumContrast = Color(0xFFD0CBB9)
val outlineDarkMediumContrast = Color(0xFFA7A392)
val outlineVariantDarkMediumContrast = Color(0xFF878374)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE7E2D5)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF2C2A21)
val inversePrimaryDarkMediumContrast = Color(0xFF504900)
val surfaceDimDarkMediumContrast = Color(0xFF15140C)
val surfaceBrightDarkMediumContrast = Color(0xFF3B3930)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF0F0E07)
val surfaceContainerLowDarkMediumContrast = Color(0xFF1D1C14)
val surfaceContainerDarkMediumContrast = Color(0xFF212017)
val surfaceContainerHighDarkMediumContrast = Color(0xFF2C2A21)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF37352C)

val primaryDarkHighContrast = Color(0xFFFFFAF2)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFD8CD76)
val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val secondaryDarkHighContrast = Color(0xFFFCFAFF)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFBCC8FF)
val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val tertiaryDarkHighContrast = Color(0xFFFDFAFF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFC0C7FF)
val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFF9F9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFBAB1)
val onErrorContainerDarkHighContrast = Color(0xFF000000)
val backgroundDarkHighContrast = Color(0xFF15140C)
val onBackgroundDarkHighContrast = Color(0xFFE7E2D5)
val surfaceDarkHighContrast = Color(0xFF15140C)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF49473A)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFAF2)
val outlineDarkHighContrast = Color(0xFFD0CBB9)
val outlineVariantDarkHighContrast = Color(0xFFD0CBB9)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE7E2D5)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF2F2B00)
val surfaceDimDarkHighContrast = Color(0xFF15140C)
val surfaceBrightDarkHighContrast = Color(0xFF3B3930)
val surfaceContainerLowestDarkHighContrast = Color(0xFF0F0E07)
val surfaceContainerLowDarkHighContrast = Color(0xFF1D1C14)
val surfaceContainerDarkHighContrast = Color(0xFF212017)
val surfaceContainerHighDarkHighContrast = Color(0xFF2C2A21)
val surfaceContainerHighestDarkHighContrast = Color(0xFF37352C)







